### ISSUE TITLE
Fix basil tutorial to install zos globally

### ISSUE THREAD

**Issue by roschler** [zeppelinos/basil#30]
I'm following along with the Basil tutorial.  I reached the point where I install the "zos" package with npm:

$ npm install zos
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
basil@1.0.0 /home/robert/Documents/GitHub/ME/zeppelin-os-work/basil
└─┬ zos@1.0.0 
  └─┬ truffle-core@4.1.11
    └─┬ ethpm-registry@0.0.10
      ├─┬ solidity-sha3@0.4.1
      │ └─┬ web3@0.16.0
      │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#c7a38de919ed75e6fb6ba38051986e294b328df9)
      ├─┬ truffle-artifactor@2.1.5
      │ └─┬ truffle-contract@2.0.5
      │   └─┬ web3@0.20.6
      │     └── bignumber.js@2.0.7  (git+https://github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934)
      ├─┬ truffle-contract@1.1.11
      │ ├─┬ truffle-blockchain-utils@0.0.1
      │ │ └─┬ web3@0.18.4
      │ │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
      │ └─┬ web3@0.16.0
      │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#c7a38de919ed75e6fb6ba38051986e294b328df9)
      └─┬ web3@0.18.4
        └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN webpack-cli@2.1.4 requires a peer of webpack@^4.0.0 but none was installed.
npm WARN basil@1.0.0 No description
npm WARN basil@1.0.0 No repository field.
```
However when I try to run zos from the command line, it can't be found:
```
No such file or directory
```
I then tried installing zos globally:
```
$ npm install -g zos
```
Now it can find zos but I was getting the following error when I ran the zos command:
```
/home/robert/.nvm/versions/node/v6.7.0/lib/node_modules/zos/node_modules/zos-lib/lib/test/helpers/assertRevert.js:7
exports.default = async function assertRevert(promise, invariants = () => {}) {
                        ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robert/.nvm/versions/node/v6.7.0/lib/node_modules/zos/node_modules/zos-lib/lib/test/index.js:12:21)
    at Module._compile (module.js:556:32)
```
I then uninstalled it and changed my active Node.js version from **6.7.0** to **8.11.1**.  I then reinstalled it locally.  That didn't work.  I then installed it **globally** again and this time, using Node.JS **8.11.1**, everything worked and I could create my zos.json file using the zos utility.

Perhaps the Basil tutorial needs to be updated to tell people to install the package **globally** and not locally?:
```
npm install -g zos
```

**Comment by roschler** [comment]
The other solution is to use the **npx** utility with each zos command, instead of doing a global installation of the `zos` package
